scrapy_settings = {
    "HTTPERROR_ALLOW_ALL": False,
    "BOT_NAME": "cdl_awo_funding_crawler",
    "LOG_LEVEL": "INFO",
    "CONCURRENT_REQUESTS": 1,
    "CONCURRENT_REQUESTS_PER_DOMAIN": 1,
    "LOGSTATS_INTERVAL": 20.0,
    "COOKIES_ENABLED": False,
    "DOWNLOAD_DELAY": 3.0,
    "RANDOMIZE_DOWNLOAD_DELAY": True,
    "AUTOTHROTTLE_ENABLED": True,
    "AUTOTHROTTLE_START_DELAY": 3.0,
    "AUTOTHROTTLE_MAX_DELAY": 60.0,
    "AUTOTHROTTLE_TARGET_CONCURRENCY": 1.0,
    "RETRY_TIMES": 5,
    "RETRY_HTTP_CODES": [500, 502, 503, 504, 408, 429, 522, 524],
    "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0 Safari/537.36",
    "DEFAULT_REQUEST_HEADERS": {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
    },
}
